### ISSUE TITLE
Feature: Add commits to release notes

### ISSUE THREAD

**Issue by ashbob999** [ashvardanian/tinysemver#14]
Currently all release notes consist of the following text:

`message = f"Release: {tag} [skip ci]"`

Which is not very descriptive, it would be better to add the commits into the releases notes as done with the changelog file. Which [semantic-release](https://github.com/semantic-release/semantic-release) did already do.

**Comment by ashvardanian** [comment]
That should be easy to patch. Want to try, @ashbob999?

**Comment by ashbob999** [comment]
Can do, would you still want the original message in it?

**Comment by ashbob999** [comment]
Also, should the commit hash be part of the description? @ashvardanian

**Comment by ashvardanian** [comment]
A short-hash forming a GitHub link can be handy.

**Comment by ashbob999** [comment]
()
